Add Description and ProducesResponseType
Svyatopes/SpaceZD pull request #76
Opened 2022-03-01 18:59 UTC by Stepa28

2022-03-01 19:43 UTC, Svyatopes requested changes

2022-03-01 19:43 UTC, Svyatopes commented on SpaceZD.API/Controllers/CarriageTypesController.cs
> +    [SwaggerOperation(Summary = "Get all deleted сarriage types")]
напиши что это только для админа

2022-03-01 19:43 UTC, Svyatopes commented on SpaceZD.API/Controllers/CarriageTypesController.cs
> +    [SwaggerOperation(Summary = "Restoring carriage type by id")]
тоже, что только для админа надо уточнить

2022-03-01 19:43 UTC, Svyatopes commented on SpaceZD.API/Controllers/RoutesController.cs
> +    [SwaggerOperation(Summary = "Get all deleted routes")]
опять

2022-03-01 19:43 UTC, Svyatopes commented on SpaceZD.API/Controllers/RoutesController.cs
> +    [SwaggerOperation(Summary = "Editing route by id")]
может написать тут что именно можно изменять? Хм, подумой

2022-03-01 19:43 UTC, Svyatopes commented on SpaceZD.API/Controllers/RoutesController.cs
> +    [SwaggerOperation(Summary = "Restoring route by id")]
только админ

2022-03-01 19:43 UTC, Svyatopes commented on SpaceZD.API/Controllers/StationsController.cs
> +    [SwaggerOperation(Summary = "Get all deleted stations")]
админ

2022-03-01 19:43 UTC, Svyatopes commented on SpaceZD.API/Controllers/TripStationsController.cs
> +    [SwaggerOperation(Summary = "Get ready platform by trip station id")]
вообще Ready platforms это чета странное, может лучше available platforms?

2022-03-01 19:43 UTC, Svyatopes commented on SpaceZD.API/Controllers/TripsController.cs
> +    [SwaggerOperation(Summary = "Get all trips from select date")]
from selected date это начиная с такой даты и по сегодняшний день? Может лучше для конкретного дня выдавать, а то там список будет жопа

2022-03-01 19:43 UTC, Svyatopes commented on SpaceZD.API/Controllers/TripsController.cs
> +    [SwaggerOperation(Summary = "Get seats from trip by id and start/end station id")]
просто получаем сидения? Надо указать что мы получаем их статус - занято оно или ещё нет

2022-03-01 19:43 UTC, Svyatopes commented on SpaceZD.API/Controllers/TripsController.cs
> +    [SwaggerOperation(Summary = "Restoring trip by id")]
только админ

2022-03-02 08:55 UTC, Stepa28 commented on SpaceZD.API/Controllers/RoutesController.cs
> +    [SwaggerOperation(Summary = "Editing route by id")]
мы принимаем RouteInputModel и не сможем принять ничего иного, если человеку нужно, он посмотрит схему, если не нужно то ненужно засорять аннотации

2022-03-02 12:19 UTC, Svyatopes approved these changes

2022-03-02 12:19 UTC, merged